version: '3.8'

services:
  rstudio:
    platform: linux/arm64
    image: jflournoy/verse-cmdstan:cppopt
    privileged: true
    ports:
      - "9210:8787"
    environment:
      - DISABLE_AUTH=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${HOME}/code:/home/rstudio/code"
      - "${HOME}/data:/home/rstudio/data"
      - "${HOME}/R:/home/rstudio/R"
      - "./init.sh:/docker-entrypoint.d/init.sh"
