version: '3.8'

services:
  rstudio:
    image: jflournoy/verse-cmdstan:2.34.1
    ports:
      - "9210:8787"
    environment:
      - DISABLE_AUTH=true
    volumes:
      - "${HOME}/code:/home/rstudio/code"
      - "${HOME}/data:/home/rstudio/data"
      - "${HOME}/r_verse-cmdstan_4.3:/home/rstudio/R/x86_64-pc-linux-gnu-library/4.3"
